# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:  
- bash: |
    mkdir /tmp/.keys/
    ssh-keygen -t rsa -b 4096 -C 'jasu@jasu' -N '' -f /tmp/.keys/id_rsa
    echo '##vso[task.setvariable variable=sshPrivKeyCluster;isoutput=true;issecret=true;isreadonly=true]'$(cat /tmp/.keys/id_rsa)
    echo '##vso[task.setvariable variable=sshPubKeyCluster;isoutput=true;issecret=true;isreadonly=true]'$(cat /tmp/.keys/id_rsa.pub)
    rm -rf /tmpfs/.keys/
  displayName: 'SshKeygenScript'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Relativity-conn'
    subscriptionId: 'bb5683f7-8679-4ecd-a524-71f3a3291863'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Relativity-rg'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/jviding/Relativity/main/deployment/azuredeploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/jviding/Relativity/main/deployment/azuredeploy.parameters.json'
    overrideParameters: '-sshPrivKeyCluster -$(sshPrivKeyCluster) -sshPubKeyCluster -$(sshPubKeyCluster)'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'