# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: test
  value: "testValue"

steps:  
- bash: |
    mkdir /tmp/.keys/
    ssh-keygen -m PEM -t rsa -b 4096 -C 'jasu@jasu23' -N '' -f /tmp/.keys/id_rsa
    PRIVATE_KEY=$(cat /tmp/.keys/id_rsa)
    PUBLIC_KEY=$(ls /tmp/.keys/)
    echo '##vso[task.setvariable variable=sshPrivKeyCluster;issecret=true;isreadonly=true]'$(cat /tmp/.keys/id_rsa)
    echo '##vso[task.setvariable variable=sshPubKeyCluster;isreadonly=true]'$(cat /tmp/.keys/id_rsa.pub)
    #echo '##vso[task.setvariable variable=test]'$(cat /tmp/.keys/id_rsa.pub)
    # echo "##vso[task.setvariable variable=test]$(echo 'asdSome')" Tämä toimii
    echo "##vso[task.setvariable variable=test]${PUBLIC_KEY}"
    rm -rf /tmpfs/.keys/
  name: 'KeyGenerator'
  failOnStderr: true
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Relativity-conn'
    subscriptionId: 'bb5683f7-8679-4ecd-a524-71f3a3291863'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Relativity-rg'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/jviding/Relativity/main/deployment/azuredeploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/jviding/Relativity/main/deployment/azuredeploy.parameters.json'
    overrideParameters: '-sshPrivKeyCluster asd -sshPubKeyCluster asd -sshPubKey $(test)'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'