trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:  
- bash: |
    mkdir /tmp/.keys/
    ssh-keygen -m PEM -t rsa -b 4096 -C 'jasu@jasu' -N '' -f /tmp/.keys/id_rsa
    PRIVATE_KEY_BASE64=$(cat /tmp/.keys/id_rsa | base64)
    PUBLIC_KEY_BASE64=$(cat /tmp/.keys/id_rsa.pub | base64)
    echo "##vso[task.setvariable variable=privKeyBase64;issecret=true;isreadonly=true]${PRIVATE_KEY_BASE64}"
    echo "##vso[task.setvariable variable=pubKeyBase64;isreadonly=true]${PUBLIC_KEY_BASE64}"
    echo $PUBLIC_KEY_BASE64
    rm -rf /tmpfs/.keys/
  name: 'KeyGenerator'
  failOnStderr: true
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Relativity-conn'
    subscriptionId: 'bb5683f7-8679-4ecd-a524-71f3a3291863'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Relativity-rg'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/jviding/Relativity/main/deployment/azuredeploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/jviding/Relativity/main/deployment/azuredeploy.parameters.json'
    overrideParameters: '-sshPrivKeyBase64 $(privKeyBase64) -sshPubKeyBase64 $(pubKeyBase64)'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'