version: '3.8'

services:

  # FRONT
  
#  front:
#    build:
#      context: ./web-front
#      dockerfile: dev.Dockerfile
#    restart: always
#    volumes: 
#      - ./web-front:/app
#    ports:
#      - "8080:8080"
#    working_dir: /app
#   command: sleep 3600 #npm start

  # API

  api-private:
    build:
      context: ./web-api/private
      dockerfile: dev.Dockerfile
    restart: always
    volumes: 
      - ./web-api/private:/app
      # TODO: Secrets/configurations
    ports:
      - "8082:8082"
    working_dir: /app
    command: sleep 3600 #python3 -u manage.py runserver 0.0.0.0:8081

#  api-public:
#    build:
#      context: ./web-api/public
#      dockerfile: dev.Dockerfile
#    restart: always
#    volumes: 
#      - ./web-api/public:/app
      # TODO: Secrets/configurations
#    ports:
#      - "8081:8081"
#    working_dir: /app
#    command: sleep 3600 #python3 -u manage.py runserver 0.0.0.0:8081


  # DATABASE
  # TODO...

  # DATA COLLECTORS

#  bonds:
#    build:
#      context: ./data-collectors/bonds
#      dockerfile: dev.Dockerfile
#    restart: always
#    volumes: 
#      - ./data-collectors/bonds:/scripts
#    command: sleep 36000

#  commodities:
#    build:
#      context: ./data-collectors/commodities
#      dockerfile: dev.Dockerfile
#    restart: always
#    volumes: 
#      - ./data-collectors/commodities:/scripts
#    command: sleep 36000

#  currencies:
#    build:
#      context: ./data-collectors/currencies
#      dockerfile: dev.Dockerfile
#    restart: always
#    volumes: 
#      - ./data-collectors/currencies:/scripts
#    command: sleep 36000

#  indexes:
#    build:
#      context: ./data-collectors/indexes
#      dockerfile: dev.Dockerfile
#    restart: always
#    volumes:
#      - ./data-collectors/indexes:/scripts
#    command: sleep 36000